name: Update pnpm lockfile
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install (no frozen)
        run: pnpm install --no-frozen-lockfile
      - name: Commit lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pnpm-lock.yaml
          git commit -m "chore: update pnpm-lock after overrides" || echo "No changes"
          git push
